using System.ComponentModel.DataAnnotations;

namespace LibraryProjectModule12.ViewModels
{
    /// <summary>
    /// EventViewModel is a class that represents the data structure for an event in the context of a library project. It contains properties that define the characteristics of an event, such as its unique identifier (Id), name (Name), description (Description), and date (Date). Each property is decorated with data annotations to enforce validation rules and provide display names for user interfaces. This view model is typically used to transfer data between the application and the user interface when creating, editing, or displaying event information.
    /// </summary>
    public class EventViewModel
    {
        // The unique identifier for the event. This property is of type int and is used to distinguish each event in the system. It is typically generated by the database when a new event is created and serves as the primary key for the event entity.
        public int Id { get; set; }

        [Required(ErrorMessage ="Името е задължително")]
        [MaxLength(256)]
        [Display(Name = "Event Name")]
        public string Name { get; set; } = string.Empty;
        // The description of the event. This property is required, has a maximum length of 2048 characters, and is displayed with the name "Event Description". It provides additional details about the event, such as its purpose, activities, or any other relevant information that attendees might need to know.
        [Required(ErrorMessage = "Описанието е задължително")]
        [MaxLength(2048)]
        [Display(Name = "Event Description")]
        public string? Description { get; set; }
        // The date and time of the event. This property is required and is displayed with the name "Event Date and Time". It indicates when the event is scheduled to take place, allowing attendees to plan accordingly and ensuring that the event is organized at the appropriate time.
        [Required(ErrorMessage = "Датата е задължителна")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Event Date and Time")]
        public DateTime Date { get; set; }
    }
}
