// <auto-generated />
using System;
using LibraryProjectModule12.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryProjectModule12.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210150722_RefreshSnapshot")]
    partial class RefreshSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryProjectModule12.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateRegistrated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "British India",
                            IsDeleted = false,
                            LastName = "Orwell",
                            Name = "George"
                        },
                        new
                        {
                            Id = 2,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Rowling",
                            Name = "J.K."
                        },
                        new
                        {
                            Id = 3,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "King",
                            Name = "Stephen"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Russian SFSR",
                            IsDeleted = false,
                            LastName = "Asimov",
                            Name = "Isaac"
                        },
                        new
                        {
                            Id = 5,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Christie",
                            Name = "Agatha"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Kingdom of Great Britain",
                            IsDeleted = false,
                            LastName = "Austen",
                            Name = "Jane"
                        },
                        new
                        {
                            Id = 7,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Twain",
                            Name = "Mark"
                        },
                        new
                        {
                            Id = 8,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Dickens",
                            Name = "Charles"
                        },
                        new
                        {
                            Id = 9,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Hemingway",
                            Name = "Ernest"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Kingdom of England",
                            IsDeleted = false,
                            LastName = "Shakespeare",
                            Name = "William"
                        },
                        new
                        {
                            Id = 11,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Wells",
                            Name = "H.G."
                        },
                        new
                        {
                            Id = 12,
                            Country = "Orange Free State",
                            IsDeleted = false,
                            LastName = "Tolkien",
                            Name = "J.R.R."
                        },
                        new
                        {
                            Id = 13,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Lee",
                            Name = "Harper"
                        },
                        new
                        {
                            Id = 14,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Fitzgerald",
                            Name = "F. Scott"
                        },
                        new
                        {
                            Id = 15,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Bradbury",
                            Name = "Ray"
                        },
                        new
                        {
                            Id = 16,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Pratchett",
                            Name = "Terry"
                        },
                        new
                        {
                            Id = 17,
                            Country = "Ireland",
                            IsDeleted = false,
                            LastName = "Lewis",
                            Name = "C.S."
                        },
                        new
                        {
                            Id = 18,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Doyle",
                            Name = "Arthur Conan"
                        },
                        new
                        {
                            Id = 19,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Angelou",
                            Name = "Maya"
                        },
                        new
                        {
                            Id = 20,
                            Country = "Russian Empire",
                            IsDeleted = false,
                            LastName = "Tolstoy",
                            Name = "Leo"
                        },
                        new
                        {
                            Id = 21,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Woolf",
                            Name = "Virginia"
                        },
                        new
                        {
                            Id = 22,
                            Country = "Ireland",
                            IsDeleted = false,
                            LastName = "Wilde",
                            Name = "Oscar"
                        },
                        new
                        {
                            Id = 23,
                            Country = "Republic of Florence",
                            IsDeleted = false,
                            LastName = "Alighieri",
                            Name = "Dante"
                        },
                        new
                        {
                            Id = 24,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Dickinson",
                            Name = "Emily"
                        },
                        new
                        {
                            Id = 25,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Andrews",
                            Name = "Virginia"
                        },
                        new
                        {
                            Id = 26,
                            Country = "Colombia",
                            IsDeleted = false,
                            LastName = "García Márquez",
                            Name = "Gabriel"
                        },
                        new
                        {
                            Id = 27,
                            Country = "Canada",
                            IsDeleted = false,
                            LastName = "Atwood",
                            Name = "Margaret"
                        },
                        new
                        {
                            Id = 28,
                            Country = "Japan",
                            IsDeleted = false,
                            LastName = "Murakami",
                            Name = "Haruki"
                        },
                        new
                        {
                            Id = 29,
                            Country = "French Algeria",
                            IsDeleted = false,
                            LastName = "Camus",
                            Name = "Albert"
                        },
                        new
                        {
                            Id = 30,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Gaiman",
                            Name = "Neil"
                        },
                        new
                        {
                            Id = 31,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Poe",
                            Name = "Edgar Allan"
                        },
                        new
                        {
                            Id = 32,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Melville",
                            Name = "Herman"
                        },
                        new
                        {
                            Id = 33,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Steinbeck",
                            Name = "John"
                        },
                        new
                        {
                            Id = 34,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Plath",
                            Name = "Sylvia"
                        },
                        new
                        {
                            Id = 35,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Martin",
                            Name = "George R.R."
                        },
                        new
                        {
                            Id = 36,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Vonnegut",
                            Name = "Kurt"
                        },
                        new
                        {
                            Id = 37,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Morrison",
                            Name = "Toni"
                        },
                        new
                        {
                            Id = 38,
                            Country = "Ireland",
                            IsDeleted = false,
                            LastName = "Joyce",
                            Name = "James"
                        },
                        new
                        {
                            Id = 39,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Salinger",
                            Name = "J.D."
                        },
                        new
                        {
                            Id = 40,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Alcott",
                            Name = "Louisa May"
                        },
                        new
                        {
                            Id = 41,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Ellison",
                            Name = "Ralph"
                        },
                        new
                        {
                            Id = 42,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Hurston",
                            Name = "Zora Neale"
                        },
                        new
                        {
                            Id = 43,
                            Country = "Russian Empire",
                            IsDeleted = false,
                            LastName = "Nabokov",
                            Name = "Vladimir"
                        },
                        new
                        {
                            Id = 44,
                            Country = "Austria-Hungary",
                            IsDeleted = false,
                            LastName = "Kafka",
                            Name = "Franz"
                        },
                        new
                        {
                            Id = 46,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Shelley",
                            Name = "Mary"
                        },
                        new
                        {
                            Id = 47,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Wharton",
                            Name = "Edith"
                        },
                        new
                        {
                            Id = 48,
                            Country = "Poland",
                            IsDeleted = false,
                            LastName = "Conrad",
                            Name = "Joseph"
                        },
                        new
                        {
                            Id = 49,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "Faulkner",
                            Name = "William"
                        },
                        new
                        {
                            Id = 50,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "London",
                            Name = "Jack"
                        },
                        new
                        {
                            Id = 51,
                            Country = "France",
                            IsDeleted = false,
                            LastName = "Dumas",
                            Name = "Alexandre"
                        },
                        new
                        {
                            Id = 52,
                            Country = "France",
                            IsDeleted = false,
                            LastName = "Hugo",
                            Name = "Victor"
                        },
                        new
                        {
                            Id = 53,
                            Country = "France",
                            IsDeleted = false,
                            LastName = "Proust",
                            Name = "Marcel"
                        },
                        new
                        {
                            Id = 54,
                            Country = "France",
                            IsDeleted = false,
                            LastName = "Verne",
                            Name = "Jules"
                        },
                        new
                        {
                            Id = 55,
                            Country = "United States",
                            IsDeleted = false,
                            LastName = "James",
                            Name = "Henry"
                        },
                        new
                        {
                            Id = 56,
                            Country = "Scotland",
                            IsDeleted = false,
                            LastName = "Stevenson",
                            Name = "Robert Louis"
                        },
                        new
                        {
                            Id = 57,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Brontë",
                            Name = "Charlotte"
                        },
                        new
                        {
                            Id = 58,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Brontë",
                            Name = "Emily"
                        },
                        new
                        {
                            Id = 45,
                            Country = "United Kingdom",
                            IsDeleted = false,
                            LastName = "Brontë",
                            Name = "Anne"
                        });
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.EventUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("EventUsers");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ShelfType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Book", b =>
                {
                    b.HasOne("LibraryProjectModule12.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryProjectModule12.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.EventUser", b =>
                {
                    b.HasOne("LibraryProjectModule12.Models.Event", "Event")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryProjectModule12.Models.ApplicationUser", "User")
                        .WithMany("EventUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Library", b =>
                {
                    b.HasOne("LibraryProjectModule12.Models.Book", "Book")
                        .WithMany("Libraries")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryProjectModule12.Models.ApplicationUser", "User")
                        .WithMany("Libraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Review", b =>
                {
                    b.HasOne("LibraryProjectModule12.Models.Library", "Library")
                        .WithMany("Reviews")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LibraryProjectModule12.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LibraryProjectModule12.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryProjectModule12.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LibraryProjectModule12.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.ApplicationUser", b =>
                {
                    b.Navigation("EventUsers");

                    b.Navigation("Libraries");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Book", b =>
                {
                    b.Navigation("Libraries");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Event", b =>
                {
                    b.Navigation("EventUsers");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryProjectModule12.Models.Library", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
