using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibraryProjectModule12.Models
{
    /// <summary>
    /// Event class represents an event entity in the library system. It contains properties such as Id, Name, Description, Date, IsDeleted, and a collection of EventUser to represent the many-to-many relationship between events and users.
    /// </summary>
    public class Event
    {
        // The unique identifier for the event. This property is required and is generated by the database as an identity column.
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        // The name of the event. This property is required and has a maximum length of 256 characters.
        [Required]
        [MaxLength(256)]
        [Display(Name = "Event Name")]
        public string Name { get; set; } = string.Empty;
        // The description of the event. This property is required and has a maximum length of 2048 characters.
        [Required]
        [MaxLength(2048)]
        [Display(Name = "Event Description")]
        public string? Description { get; set; }
        // The date and time of the event. This property is required and is displayed with the name "Event Date and Time".
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Event Date and Time")]
        public DateTime Date { get; set; }
        // A boolean property indicating whether the event is deleted. This property is required.
        [Required]
        public bool IsDeleted { get; set; }
        // A collection of EventUser representing the many-to-many relationship between events and users. This property is initialized to an empty list to avoid null reference issues.
        public ICollection<EventUser> EventUsers { get; set; } = new List<EventUser>();
    }
}