using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibraryProjectModule12.Models
{
    /// <summary>
    /// EventUser class represents the many-to-many relationship between events and users in the library system. It contains properties such as Id, UserId, EventId, IsDeleted, and navigation properties for User and Event. This class allows us to track which users are associated with which events and whether the association has been marked as deleted.
    /// </summary>
    public class EventUser
    {
        // The unique identifier for the EventUser relationship. This property is required and is generated by the database as a GUID.
        [Required]
        public Guid Id { get; set; }
        // The foreign key for the user associated with the event. This property is required and references the ApplicationUser entity.
        [Required]
        [ForeignKey(nameof(User))]
        public string UserId { get; set; }
        // Navigation property for the user associated with the event. This property is optional and allows access to the related ApplicationUser entity.
        public ApplicationUser? User { get; set; }
        // The foreign key for the event associated with the user. This property is required and references the Event entity.
        [Required]
        [ForeignKey(nameof(Event))]
        public int EventId { get; set; }
        // Navigation property for the event associated with the user. This property is optional and allows access to the related Event entity.
        public Event? Event { get; set; }
        // A boolean property indicating whether the EventUser relationship has been marked as deleted. This property is required and allows us to track the deletion status of the association between users and events.
        [Required]
        public bool IsDeleted { get; set; }
    }
}